# Generated by Django 2.2.4 on 2022-01-16 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20220116_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='member',
            field=models.IntegerField(choices=[(1, '혼자만의 시간'), (2, '2명'), (3, '3명'), (4, '4명'), (5, '5명 이상')], default=None),
        ),
    ]
