# Generated by Django 2.2.4 on 2022-01-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20220117_0031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='message',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tag_set',
        ),
        migrations.AlterField(
            model_name='post',
            name='member',
            field=models.IntegerField(choices=[(1, '혼자'), (2, '둘이'), (3, '셋이'), (4, '넷'), (5, '다섯'), (6, '여섯'), (7, '일곱'), (8, '여덟')], default=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
